import "~/styles/globals.css";

import { ClerkProvider } from '@clerk/nextjs'
import { esES } from "@clerk/localizations";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={esES}
    appearance={{
      elements:{
        footer: 'hidden',
      },
    }}> 
        <html lang="en">
          <body className={`font-sans ${inter.variable}  min-h-screen`}>
            <Providers>
              <TRPCReactProvider cookies={cookies().toString()}>
                {children}
              </TRPCReactProvider>
            </Providers>
          </body>
        </html>
    </ClerkProvider>
  );
}
